467 player and outfit counts look wonky on mobile
ps2alerts/website pull request #472
Opened 2022-08-01 21:04 UTC by oslohes123

Updated on styling need review on how to change it further

Or maybe a simpler version may be 
![image](https://user-images.githubusercontent.com/61867169/182245632-f25e50e5-622a-462d-ba00-d2ea1438d5db.png)
This is on Iphone SE which has a very small x-axis
![image](https://user-images.githubusercontent.com/61867169/182245705-a8d2c8ac-edab-4611-9151-c61ec11a53fb.png)
Looks much nicer on a larger phone where the whole line is visible
And on ipad
![image](https://user-images.githubusercontent.com/61867169/182245792-76447c4e-e222-440e-ac5f-6f37f69b57b9.png)
And then on PC it looks fine
![image](https://user-images.githubusercontent.com/61867169/182245875-ba05272f-91a0-4ac5-9b38-bfba31a537ec.png)
Also this reduces the code complexity a bit since no breakpoints are needed as these are the same styles that are themselves adapting to the size of the display

2022-08-01 22:32 UTC, Maelstromeous requested changes
Looking much better yeah, just a few minor details to fix

2022-08-01 22:32 UTC, Maelstromeous commented on components/alert/AlertCharacterMetrics.vue
> +        <div class = "p-2">Player Counts</div>
Extra spacing here for no reason

2022-08-01 22:32 UTC, Maelstromeous commented on components/alert/AlertCharacterMetrics.vue
> +      <div class="col-start-1 col-span-full mb-2 flex flex-wrap justify-center ">
Not sure if `col-start-1` is required if you're also using `col-span-full`, think it's redundant. ALso note extra space on the end

2022-08-02 08:02 UTC, oslohes123 commented
There shouldn't be any extra spaces I couldn't find the second one you said, if you view the file itself in the branch there are no unecessary spaces that I can see. Also I have removed the col-start-1 as col-span-1 translates to 1 / -1 where 1 tells the div to start at the beginning anyway cheers !

2022-08-02 08:57 UTC, Maelstromeous commented
There's still extra spaces on line 14

2022-08-02 09:14 UTC, oslohes123 commented
> There's still extra spaces on line 14

How about now?

2022-08-02 09:15 UTC, Maelstromeous approved these changes
LGTM

2022-08-02 09:16 UTC, merged